### ISSUE TITLE
Not able to Login through google 

### ISSUE THREAD

**Issue by ankitkumar1302** [ItamiOMW/CalorieTracker#35]
# Bug Report: Google Sign-In Button Not Working

## Description
The Google Sign-In button on the application is not functioning as expected. When clicked, it does not initiate the sign-in process or redirect the user to the Google authentication page.

## Steps to Reproduce
1. Open the application.
2. Navigate to the login/sign-in page.
3. Click on the "Sign in with Google" button.

## Expected Behavior
The user should be redirected to the Google authentication page to complete the sign-in process.

## Actual Behavior
Clicking the "Sign in with Google" button produces no response. There are no error messages or visible feedback indicating the action was registered.

## Environment
- **App Version:** Latest
- **OS:** Android 10
 

## Video

https://github.com/ItamiOMW/CalorieTracker/assets/95230112/0d7de2a6-5361-4b76-bfd9-a064137aeeef

Please investigate this issue and provide a fix or workaround. Thank you!

**Comment by ItamiOMW** [comment]
Hi! Thank you for reporting the problem. This is because my Google OAuth is still in test publishing status and only allows test users to sign in using Google.  I was planning to go through verification soon, and as a temporary solution, I can add you as a test user or you can just sign in using email.

**Comment by ankitkumar1302** [comment]
OK, for that also 1 more thing I want to ask 
I am also facing some issues in the ktor project 
I will also share logs if you want so.

**Comment by ItamiOMW** [comment]
> OK, for that also 1 more thing I want to ask 
> I am also facing some issues in the ktor project 
> I will also share logs if you want so.

That would be great

**Comment by ankitkumar1302** [comment]
ok, I will send it to the particular project for better clarification.
